### PR TITLE
Fix xdebug install from github

### PR DESCRIPTION
**Pull request by podarok**

### CODE REVIEW

**Comment by derickr** [comment]
Please don't do this. The package on GitHub isn't necessarily the same as on the Xdebug website or pecl website. *if* you don't want the one from xdebug.org, use the one from PECL.

**Comment by podarok** [comment]
we are using 2.2.5 which is the same, so we are good here @derickr

**Comment by derickr** [comment]
2.2.5 is more than 2 years old. That's not a good idea either.

**Comment by podarok** [comment]
@derickr it will be not a good idea when it stops working ))))

**Comment by derickr** [comment]
I've no idea what you mean by that.

**Comment by podarok** [comment]
))) @derickr I meant we are fine with an old version. Stability is more preferred for us than racing for new versions.

**Pull request merged**
