### PR TITLE
Replace PropeopleExtension with TqExtension. Add pretty formatter for output.

### PR DESCRIPTION
**Pull request by Andrei-Colesnic**

### CODE REVIEW

**Comment by podarok** [comment]
ok to test

**Comment by podarok** [comment]
@Andrei-Colesnic please update upstream. It has a fix for xdebug #455

**Comment by Andrei-Colesnic** [comment]
Will do

**Comment by Andrei-Colesnic** [comment]
@podarok The build status report seems to be taking too long. Can you look into this, please? Thank you.

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
@Andrei-Colesnic  the issue was with CI server disk full........... Should be fine in a few minutes

**Comment by podarok** [comment]
retest this please

**Pull request merged**
