### PR TITLE
Do a provision only if it manually requested ("vagrant provision" executed)

### PR DESCRIPTION
**Pull request by BR0kEN-**
Execute the VM provisioning when user manually executed the `vagrant provision` to get rid from additional environment variable - `FORCE_PROVISION`, - which adds more complexity to the application.

### CODE REVIEW

**Comment by BR0kEN-** [comment]
@podarok, any reaction on this?

**Comment by podarok** [comment]
@BR0kEN- what about vagrant up --provision?
I guess old approach if more better

**Comment by BR0kEN-** [comment]
@podarok We are not able to use custom arguments/options for `vagrant` command.

**Comment by BR0kEN-** [comment]
@podarok, By my opinion, old (current) approach complicates the project. We need to keep in mind/remember environment variable. Instead I proposing to use obvious, standard, commands: `vagrant up` - for initiating the machine with provisioned image and `vagrant provision` - for forcibly provisioning.

Also there is a my little fault - I forget that we can run `vagrant up --provision` and current implementation I proposed won't work. Will do an additional job on this.

**Comment by Sanchiz** [comment]
@podarok @BR0kEN- I confirm that currently we have only one way to provision already running VM: `vagrant destroy` and then `FORCE_PROVISION=yes vagrant up`.

It shouldn't be so, because currently commands `vagrant provision` and `vagrant run --provision` don't work.

I think approach here should be:
- When we run `vagrant up` - don't provision VM, just use Image
- When we run `vagrant up --provision` - provision VM
- When we run `vagrant provision` - provision VM

**Comment by BR0kEN-** [comment]
@Sanchiz and my implementation do the job as you described.

**Comment by podarok** [comment]
@Sanchiz 
we can run FORCE_PROVISION=yes vagrant provision

**Comment by Sanchiz** [comment]
@podarok I agree here with @BR0kEN- that it's kinda custom variable. If we can follow general rules (`vagrant provision` or `vagrant up --provision`), we should follow them, so everyone will understand how to provision VM without digging into documentation.

**Comment by Sanchiz** [comment]
Even vagrant log says this
image

**Comment by BR0kEN-** [comment]
@podarok, @Sanchiz changes from last commit allows us to use documented `--provider=<NAME>` option for choosing the VM provider.

Use `vagrant up --provider=lxc --provision` to up the machine with LXC provider and force provisioning.

Please note, that `vagrant provision --provider=lxc` will not work (previous variant with environment variable - `VAGRANT_CI=lxc vagrant provision` - didn't worked as well), but in this way Vagrant designed.

**Comment by podarok** [comment]
ok, let's live with this

**Pull request merged**
